[package]
name = "arbeitszeitdokumentationsgenerator"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
axum = "0.7.7"
axum-extra = { version = "0.9.4", features = ["form"] }
clap = { version = "4.5.20", features = ["derive", "deprecated"] }
fontdb = "0.23.0"
jiff = "0.1.13"
maud = { version = "0.26.0", features = ["axum"] }
serde = { version = "1.0.213", features = ["derive"] }
tokio = { version = "1.41.0", features = ["full"] }
typst = "0.12.0"
typst-pdf = "0.12.0"
