[package]
name = "kit_timesheets"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
axum = "0.7.5"
clap = { version = "4.5.4", features = ["derive", "deprecated"] }
comemo = "0.4.0"
fontdb = "0.16.2"
maud = { version = "0.26.0", features = ["axum"] }
time = { version = "0.3.36", features = ["macros", "formatting", "local-offset"] }
tokio = { version = "1.37.0", features = ["full"] }
typst = "0.11.0"
typst-pdf = "0.11.0"
